import axios from 'axios'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import prisma from 'lib/prisma'
// import { User } from '@prisma/client'

const fetchUsers = async () => {
  return axios.post('/api/master-scoreboard/users', {}, {
    headers: {
      authorization: `Bearer ${process.env.NEXT_PUBLIC_API_SECRET}`
    }
  })
    .catch(err => {
      throw (err)
    })
}

const fetchComps = async () => {
  return axios.post('/api/master-scoreboard/comps', {}, {
    headers: {
      authorization: `Bearer ${process.env.NEXT_PUBLIC_API_SECRET}`
    }
  })
    .catch(err => {
      throw (err)
    })
}

export default function Home({ users }: { users: any[] }) {
  const handleFetchUsers = async (e) => {
    e.preventDefault()
    const users = await fetchUsers()
    return users.data
  }

  const handleFetchComps = async (e) => {
    e.preventDefault()
    const comps = await fetchComps()
    return comps.data
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <select>
        {users.map(u => {
          return <option key={u.ms_id} value={u.ms_id}>{u.name}</option>
        })}
      </select>
      <main>
        <form onSubmit={handleFetchUsers}>
          <button type="submit">Refresh users</button>
        </form>
        <form onSubmit={handleFetchComps}>
          <button type="submit">Get comps</button>
        </form>
        <h1>
          Welcome to <a className="text-blue-600" href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Get started by editing{' '}
          <code>pages/index.js</code>
        </p>

        <div>
          <a href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}

export async function getStaticProps() {
  const users = await prisma.user.findMany()
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  // const res = await fetch('https://.../posts')
  // const posts = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      users,
    },
  }
}
